version: '3.8'
services:
  bot:
    container_name: unitebraverybot
    image: abzylicious/unitebraverybot:latest
    volumes:
      - type: bind
        source: ./data/config.json
        target: /data/config.json
      - type: bind
        source: ./data/pokemon.json
        target: /data/pokemon.json
    restart: always
    env_file:
      - .env

volumes:
  unitebraveryboty: